// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eKmbm14hvUmNq1J5N269oU
// Component: vRBf8orOA7ha
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: eKmbm14hvUmNq1J5N269oU/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: vRBf8orOA7ha/css
import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: UMZJUw_yhEgv/icon
import WeuiArrowFilledIcon from "./icons/PlasmicIcon__WeuiArrowFilled"; // plasmic-import: 10QIqdcP79wh/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: 7ZPud_k1_hEp/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: KcfzQpWiUXFU/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: DpFQJhobtUFV/icon
import FeArrowDownIcon from "./icons/PlasmicIcon__FeArrowDown"; // plasmic-import: YjaJWWv0X-cu/icon
import Line12Icon from "./icons/PlasmicIcon__Line12"; // plasmic-import: 3YbUWpx7MMmZ/icon
import IonHomeIcon from "./icons/PlasmicIcon__IonHome"; // plasmic-import: RVs7Wj_Ux_gQ/icon
import ellipse1GKfzOqbO62S from "./images/ellipse1.svg"; // plasmic-import: gKFZOqbO6_2s/picture
import logosGoogleMapsXGiXXavZUiXn from "./images/logosGoogleMaps.svg"; // plasmic-import: xGiXXavZUiXN/picture
import logosGoogleGmailRGpd4T6Ut8O from "./images/logosGoogleGmail.svg"; // plasmic-import: rGpd4_t6Ut8O/picture
import frame13QWxCCt9Y8Yo from "./images/frame13.svg"; // plasmic-import: QWxCCt9Y8yo-/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"desktop1"}
            data-plasmic-override={overrides.desktop1}
            className={classNames(projectcss.all, sty.desktop1)}
          >
            <div
              data-plasmic-name={"rectangle37"}
              data-plasmic-override={overrides.rectangle37}
              className={classNames(projectcss.all, sty.rectangle37)}
            >
              <div
                data-plasmic-name={
                  "toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes"
                }
                data-plasmic-override={
                  overrides.toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes
                )}
              >
                {
                  "To apply quantitative modeling and data analysis techniques to the solution of real-world business problems, communicate findings, and effectively present results using data visualization techniques.\nTo demonstrate knowledge of statistical data analysis techniques utilized in business decision making.\nTo apply principles of Data Science to analyze the business problems.\nTo develop a basic understanding of the building blocks of Artificial Intelligence as presented in terms of intelligent agents: search, knowledge representation, inference, logic, and learning.\nTo apply algorithms to build machine intelligence.\nTo characterize machine learning algorithms as supervised, semi-supervised, and unsupervised.\nTo effectively use machine learning toolboxes.\n"
                }
              </div>
            </div>
            <div
              data-plasmic-name={"rectangle38"}
              data-plasmic-override={overrides.rectangle38}
              className={classNames(projectcss.all, sty.rectangle38)}
            />

            <div
              data-plasmic-name={"rectangle35"}
              data-plasmic-override={overrides.rectangle35}
              className={classNames(projectcss.all, sty.rectangle35)}
            />

            <div
              data-plasmic-name={"rectangle39"}
              data-plasmic-override={overrides.rectangle39}
              className={classNames(projectcss.all, sty.rectangle39)}
            />

            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"rectangle2"}
                data-plasmic-override={overrides.rectangle2}
                className={classNames(projectcss.all, sty.rectangle2)}
              />

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                data-plasmic-name={"rectangle5"}
                data-plasmic-override={overrides.rectangle5}
                className={classNames(projectcss.all, sty.rectangle5)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oBlwu
                )}
              >
                {"\u00a9 Web Development Cell, NIT Sikkim (2023)"}
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame9"}
                data-plasmic-override={overrides.frame9}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame9)}
              >
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___0HJix)}
                    displayHeight={"67px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"67px"}
                    loading={"lazy"}
                    src={{
                      src: ellipse1GKfzOqbO62S,
                      fullWidth: 67,
                      fullHeight: 67,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cA1Xd
                    )}
                  >
                    {"DEPARTMENT OF COMPUTER\nSCIENCE AND ENGINEERING"}
                  </div>
                  <Line2Icon
                    className={classNames(projectcss.all, sty.svg__ma6O)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mybA0
                    )}
                  >
                    {"National Institute of Technology Sikkim"}
                  </div>
                  <div
                    data-plasmic-name={"group2"}
                    data-plasmic-override={overrides.group2}
                    className={classNames(projectcss.all, sty.group2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7Jv1J
                      )}
                    >
                      {
                        "The Department of Computer Science and Engineering (CSE) has been functioning since the inception of the Institute in the year 2010. The Department provides an outstanding teaching environment complemented by excellence in research."
                      }
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"explore"}
                  data-plasmic-override={overrides.explore}
                  className={classNames(projectcss.all, sty.explore)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <WeuiArrowFilledIcon
                      className={classNames(projectcss.all, sty.svg__kWv2)}
                      role={"img"}
                    />

                    <WeuiArrowFilledIcon
                      className={classNames(projectcss.all, sty.svg___0B8HG)}
                      role={"img"}
                    />

                    <WeuiArrowFilledIcon
                      className={classNames(projectcss.all, sty.svg__jE6YI)}
                      role={"img"}
                    />

                    <WeuiArrowFilledIcon
                      className={classNames(projectcss.all, sty.svg__hj4W5)}
                      role={"img"}
                    />
                  </Stack__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yg6Yh
                    )}
                  >
                    {"EXPLORE"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1"}
                    data-plasmic-override={overrides.frame1}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hD77G
                      )}
                    >
                      {"Homepage"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fLPjx
                      )}
                    >
                      {"TEQIR III"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__z3JQm
                      )}
                    >
                      {"KIC/ Library"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kjB6P
                      )}
                    >
                      {"Training & \nPlacement"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"department"}
                  data-plasmic-override={overrides.department}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.department)}
                >
                  <div
                    data-plasmic-name={"group1"}
                    data-plasmic-override={overrides.group1}
                    className={classNames(projectcss.all, sty.group1)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame6"}
                      data-plasmic-override={overrides.frame6}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame6)}
                    >
                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__dn5Hi)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__iDlUo)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__f5Ybx)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__lMvf)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__yOogz)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__zkH7W)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__x8No4)}
                        role={"img"}
                      />

                      <WeuiArrowFilledIcon
                        className={classNames(projectcss.all, sty.svg__xxfx)}
                        role={"img"}
                      />
                    </Stack__>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sain8
                      )}
                    >
                      {"DEPARTMENTS"}
                    </div>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame10"}
                      data-plasmic-override={overrides.frame10}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame10)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bdDz
                        )}
                      >
                        {"Civil Engineering"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uzBzq
                        )}
                      >
                        {"Electrical & Electronic \nEngineering"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hka9
                        )}
                      >
                        {"Electronic & Communication \nEngineering"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3FXn
                        )}
                      >
                        {"Mechanical Engineering"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__npoSi
                        )}
                      >
                        {"Mathematics"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1ZvWv
                        )}
                      >
                        {"Physics"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a1PTe
                        )}
                      >
                        {"Chemistry"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__teY7Z
                        )}
                      >
                        {"Humainities & Social \nScience"}
                      </div>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"syllabus"}
                  data-plasmic-override={overrides.syllabus}
                  className={classNames(projectcss.all, sty.syllabus)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame8"}
                    data-plasmic-override={overrides.frame8}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame8)}
                  >
                    <WeuiArrowFilledIcon
                      className={classNames(projectcss.all, sty.svg__eJ1F5)}
                      role={"img"}
                    />

                    <WeuiArrowFilledIcon
                      className={classNames(projectcss.all, sty.svg__xFir5)}
                      role={"img"}
                    />
                  </Stack__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__voYpa
                    )}
                  >
                    {"SYLLABUS"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mGZmq
                      )}
                    >
                      {"B.Tech"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oEyA
                      )}
                    >
                      {"M.Tech"}
                    </div>
                  </Stack__>
                </div>
                <div
                  data-plasmic-name={"people"}
                  data-plasmic-override={overrides.people}
                  className={classNames(projectcss.all, sty.people)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7LyFx
                    )}
                  >
                    {"PEOPLE"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gEcIe
                    )}
                  >
                    {"Feedback"}
                  </div>
                  <div
                    data-plasmic-name={"rectangle4"}
                    data-plasmic-override={overrides.rectangle4}
                    className={classNames(projectcss.all, sty.rectangle4)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aDrAz
                    )}
                  >
                    {"Write your Feedback"}
                  </div>
                  <VectorIcon
                    className={classNames(projectcss.all, sty.svg__wXbuX)}
                    role={"img"}
                  />

                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame11"}
                    data-plasmic-override={overrides.frame11}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame11)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zHh
                      )}
                    >
                      {"Faculty/Staff"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vK4K
                      )}
                    >
                      {"Researchers"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___88D2R
                      )}
                    >
                      {"Students"}
                    </div>
                  </Stack__>
                  <WeuiArrowFilledIcon
                    className={classNames(projectcss.all, sty.svg__zicI)}
                    role={"img"}
                  />

                  <WeuiArrowFilledIcon
                    className={classNames(projectcss.all, sty.svg__nmcGt)}
                    role={"img"}
                  />

                  <WeuiArrowFilledIcon
                    className={classNames(projectcss.all, sty.svg__u7Qc0)}
                    role={"img"}
                  />
                </div>
              </Stack__>
              <div
                data-plasmic-name={"rectangle6"}
                data-plasmic-override={overrides.rectangle6}
                className={classNames(projectcss.all, sty.rectangle6)}
              />

              <Stack__
                as={"div"}
                data-plasmic-name={"frame12"}
                data-plasmic-override={overrides.frame12}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame12)}
              >
                <div
                  data-plasmic-name={"address"}
                  data-plasmic-override={overrides.address}
                  className={classNames(projectcss.all, sty.address)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tq5Et
                    )}
                  >
                    {"Address"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tHiAy
                    )}
                  >
                    {
                      "Computer Science & Engineering Departments, \nNational Institute of Technology Sikkim,\nRavangla, Sikkim, India - 737139\n\n"
                    }
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__tpvXp)}
                    displayHeight={"33px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"30.642px"}
                    loading={"lazy"}
                    src={{
                      src: logosGoogleMapsXGiXXavZUiXn,
                      fullWidth: 30.642,
                      fullHeight: 33,
                      aspectRatio: 0.939394
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"phone"}
                  data-plasmic-override={overrides.phone}
                  className={classNames(projectcss.all, sty.phone)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hjoVb
                    )}
                  >
                    {"+9635027654"}
                  </div>
                  <Vector2Icon
                    className={classNames(projectcss.all, sty.svg___3BPdD)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fmaNr
                    )}
                  >
                    {"Phone"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"email"}
                  data-plasmic-override={overrides.email}
                  className={classNames(projectcss.all, sty.email)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sonR
                    )}
                  >
                    {"Email"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bowFi
                    )}
                  >
                    {"cse_hod@nitsikkim.ac.in"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__abz6K)}
                    displayHeight={"22.5px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"29.189px"}
                    loading={"lazy"}
                    src={{
                      src: logosGoogleGmailRGpd4T6Ut8O,
                      fullWidth: 29.189,
                      fullHeight: 22.5,
                      aspectRatio: 1.304348
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"ionCall"}
                  data-plasmic-override={overrides.ionCall}
                  className={classNames(projectcss.all, sty.ionCall)}
                />
              </Stack__>
            </div>
            <div
              data-plasmic-name={"logo1"}
              data-plasmic-override={overrides.logo1}
              className={classNames(projectcss.all, sty.logo1)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__i6Thm
              )}
            >
              {
                "Artificial Intelligence\nMachine Learning\nDeep Learning\nBig Data\nNatural Language Processing\nData Analytics"
              }
            </div>
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(projectcss.all, sty.rectangle1)}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg__cfarq)}
                role={"img"}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg__lbTHg)}
                role={"img"}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg__dwwvz)}
                role={"img"}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg__xiVEa)}
                role={"img"}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg___0P165)}
                role={"img"}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg__gylbX)}
                role={"img"}
              />

              <Line5Icon
                className={classNames(projectcss.all, sty.svg__x9S7D)}
                role={"img"}
              />

              <div
                data-plasmic-name={"component7"}
                data-plasmic-override={overrides.component7}
                className={classNames(projectcss.all, sty.component7)}
              >
                <div
                  data-plasmic-name={"rectangle8"}
                  data-plasmic-override={overrides.rectangle8}
                  className={classNames(projectcss.all, sty.rectangle8)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hhGo8
                  )}
                >
                  {"Academics"}
                </div>
              </div>
              <div
                data-plasmic-name={"component3"}
                data-plasmic-override={overrides.component3}
                className={classNames(projectcss.all, sty.component3)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8W0Gx
                  )}
                >
                  {"People"}
                </div>
                <FeArrowDownIcon
                  className={classNames(projectcss.all, sty.svg__jSpfr)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"facilities"}
                data-plasmic-override={overrides.facilities}
                className={classNames(projectcss.all, sty.facilities)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Fpmh
                  )}
                >
                  {"Facilities"}
                </div>
                <FeArrowDownIcon
                  className={classNames(projectcss.all, sty.svg__hVvGz)}
                  role={"img"}
                />
              </div>
              <div
                data-plasmic-name={"component8"}
                data-plasmic-override={overrides.component8}
                className={classNames(projectcss.all, sty.component8)}
              >
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"research"}
                  data-plasmic-override={overrides.research}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.research
                  )}
                >
                  {"Research "}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"group3"}
              data-plasmic-override={overrides.group3}
              className={classNames(projectcss.all, sty.group3)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ulg6J
                )}
              >
                {"Department of Computer Science & Engineering"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__osgYj
                )}
              >
                {"NATIONAL INSTITUTE OF TECHNOLOGY SIKKIM"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kLgtn
                )}
              >
                {
                  "\u0938\u0902\u0917\u0923\u0915 \u0935\u093f\u091c\u094d\u091e\u093e\u0928 \u090f\u0935\u0902 \u0905\u092d\u093f\u092f\u093e\u0902\u0924\u094d\u0930\u093f\u0915\u0940 \u0935\u093f\u092d\u093e\u0917"
                }
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lWk9Z
              )}
            >
              {"Data Science Laboratory"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xZamo
              )}
            >
              {"Laboratory Courses Conducted"}
            </div>
            <div
              data-plasmic-name={"component9"}
              data-plasmic-override={overrides.component9}
              className={classNames(projectcss.all, sty.component9)}
            >
              <div
                data-plasmic-name={"rectangle22"}
                data-plasmic-override={overrides.rectangle22}
                className={classNames(projectcss.all, sty.rectangle22)}
              />

              <div
                data-plasmic-name={"rectangle23"}
                data-plasmic-override={overrides.rectangle23}
                className={classNames(projectcss.all, sty.rectangle23)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eFtq5
                )}
              >
                {"Event"}
              </div>
            </div>
            <div
              data-plasmic-name={"component6"}
              data-plasmic-override={overrides.component6}
              className={classNames(projectcss.all, sty.component6)}
            >
              <div
                data-plasmic-name={"rectangle7"}
                data-plasmic-override={overrides.rectangle7}
                className={classNames(projectcss.all, sty.rectangle7)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dnGj
                )}
              >
                {"Home"}
              </div>
            </div>
            <Line12Icon
              className={classNames(projectcss.all, sty.svg__oAdl7)}
              role={"img"}
            />

            <IonHomeIcon
              className={classNames(projectcss.all, sty.svg__xnVhB)}
              role={"img"}
            />

            <div
              data-plasmic-name={"datascienceLab1"}
              data-plasmic-override={overrides.datascienceLab1}
              className={classNames(projectcss.all, sty.datascienceLab1)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8Xk2Y
              )}
            >
              {"Inside view of Data Science Laboratory"}
            </div>
            <Stack__
              as={PlasmicImg__}
              hasGap={true}
              alt={""}
              className={classNames(sty.img__mhQ4V)}
              displayHeight={"16px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"105px"}
              loading={"lazy"}
              src={{
                src: frame13QWxCCt9Y8Yo,
                fullWidth: 105,
                fullHeight: 16,
                aspectRatio: 6.5625
              }}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "desktop1",
    "rectangle37",
    "toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes",
    "rectangle38",
    "rectangle35",
    "rectangle39",
    "footer",
    "rectangle2",
    "rectangle3",
    "rectangle5",
    "frame9",
    "logo",
    "group2",
    "explore",
    "frame5",
    "frame1",
    "department",
    "group1",
    "frame6",
    "frame10",
    "syllabus",
    "frame8",
    "frame4",
    "people",
    "rectangle4",
    "frame11",
    "rectangle6",
    "frame12",
    "address",
    "phone",
    "email",
    "ionCall",
    "logo1",
    "header",
    "rectangle1",
    "component7",
    "rectangle8",
    "component3",
    "rectangle9",
    "facilities",
    "rectangle10",
    "component8",
    "rectangle11",
    "research",
    "group3",
    "component9",
    "rectangle22",
    "rectangle23",
    "component6",
    "rectangle7",
    "datascienceLab1"
  ],

  desktop1: [
    "desktop1",
    "rectangle37",
    "toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes",
    "rectangle38",
    "rectangle35",
    "rectangle39",
    "footer",
    "rectangle2",
    "rectangle3",
    "rectangle5",
    "frame9",
    "logo",
    "group2",
    "explore",
    "frame5",
    "frame1",
    "department",
    "group1",
    "frame6",
    "frame10",
    "syllabus",
    "frame8",
    "frame4",
    "people",
    "rectangle4",
    "frame11",
    "rectangle6",
    "frame12",
    "address",
    "phone",
    "email",
    "ionCall",
    "logo1",
    "header",
    "rectangle1",
    "component7",
    "rectangle8",
    "component3",
    "rectangle9",
    "facilities",
    "rectangle10",
    "component8",
    "rectangle11",
    "research",
    "group3",
    "component9",
    "rectangle22",
    "rectangle23",
    "component6",
    "rectangle7",
    "datascienceLab1"
  ],

  rectangle37: [
    "rectangle37",
    "toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes"
  ],

  toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes:
    [
      "toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes"
    ],

  rectangle38: ["rectangle38"],
  rectangle35: ["rectangle35"],
  rectangle39: ["rectangle39"],
  footer: [
    "footer",
    "rectangle2",
    "rectangle3",
    "rectangle5",
    "frame9",
    "logo",
    "group2",
    "explore",
    "frame5",
    "frame1",
    "department",
    "group1",
    "frame6",
    "frame10",
    "syllabus",
    "frame8",
    "frame4",
    "people",
    "rectangle4",
    "frame11",
    "rectangle6",
    "frame12",
    "address",
    "phone",
    "email",
    "ionCall"
  ],

  rectangle2: ["rectangle2"],
  rectangle3: ["rectangle3"],
  rectangle5: ["rectangle5"],
  frame9: [
    "frame9",
    "logo",
    "group2",
    "explore",
    "frame5",
    "frame1",
    "department",
    "group1",
    "frame6",
    "frame10",
    "syllabus",
    "frame8",
    "frame4",
    "people",
    "rectangle4",
    "frame11"
  ],

  logo: ["logo", "group2"],
  group2: ["group2"],
  explore: ["explore", "frame5", "frame1"],
  frame5: ["frame5"],
  frame1: ["frame1"],
  department: ["department", "group1", "frame6", "frame10"],
  group1: ["group1", "frame6", "frame10"],
  frame6: ["frame6"],
  frame10: ["frame10"],
  syllabus: ["syllabus", "frame8", "frame4"],
  frame8: ["frame8"],
  frame4: ["frame4"],
  people: ["people", "rectangle4", "frame11"],
  rectangle4: ["rectangle4"],
  frame11: ["frame11"],
  rectangle6: ["rectangle6"],
  frame12: ["frame12", "address", "phone", "email", "ionCall"],
  address: ["address"],
  phone: ["phone"],
  email: ["email"],
  ionCall: ["ionCall"],
  logo1: ["logo1"],
  header: [
    "header",
    "rectangle1",
    "component7",
    "rectangle8",
    "component3",
    "rectangle9",
    "facilities",
    "rectangle10",
    "component8",
    "rectangle11",
    "research"
  ],

  rectangle1: ["rectangle1"],
  component7: ["component7", "rectangle8"],
  rectangle8: ["rectangle8"],
  component3: ["component3", "rectangle9"],
  rectangle9: ["rectangle9"],
  facilities: ["facilities", "rectangle10"],
  rectangle10: ["rectangle10"],
  component8: ["component8", "rectangle11", "research"],
  rectangle11: ["rectangle11"],
  research: ["research"],
  group3: ["group3"],
  component9: ["component9", "rectangle22", "rectangle23"],
  rectangle22: ["rectangle22"],
  rectangle23: ["rectangle23"],
  component6: ["component6", "rectangle7"],
  rectangle7: ["rectangle7"],
  datascienceLab1: ["datascienceLab1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    desktop1: makeNodeComponent("desktop1"),
    rectangle37: makeNodeComponent("rectangle37"),
    toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes:
      makeNodeComponent(
        "toApplyQuantitativeModelingAndDataAnalysisTechniquesToTheSolutionOfRealWorldBusinessProblemsCommunicateFindingsAndEffectivelyPresentResultsUsingDataVisualizationTechniquesToDemonstrateKnowledgeOfStatisticalDataAnalysisTechniquesUtilizedInBusinessDecisionMakingToApplyPrinciplesOfDataScienceToAnalyzeTheBusinessProblemsToDevelopABasicUnderstandingOfTheBuildingBlocksOfArtificialIntelligenceAsPresentedInTermsOfIntelligentAgentsSearchKnowledgeRepresentationInferenceLogicAndLearningToApplyAlgorithmsToBuildMachineIntelligenceToCharacterizeMachineLearningAlgorithmsAsSupervisedSemiSupervisedAndUnsupervisedToEffectivelyUseMachineLearningToolboxes"
      ),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle35: makeNodeComponent("rectangle35"),
    rectangle39: makeNodeComponent("rectangle39"),
    footer: makeNodeComponent("footer"),
    rectangle2: makeNodeComponent("rectangle2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame9: makeNodeComponent("frame9"),
    logo: makeNodeComponent("logo"),
    group2: makeNodeComponent("group2"),
    explore: makeNodeComponent("explore"),
    frame5: makeNodeComponent("frame5"),
    frame1: makeNodeComponent("frame1"),
    department: makeNodeComponent("department"),
    group1: makeNodeComponent("group1"),
    frame6: makeNodeComponent("frame6"),
    frame10: makeNodeComponent("frame10"),
    syllabus: makeNodeComponent("syllabus"),
    frame8: makeNodeComponent("frame8"),
    frame4: makeNodeComponent("frame4"),
    people: makeNodeComponent("people"),
    rectangle4: makeNodeComponent("rectangle4"),
    frame11: makeNodeComponent("frame11"),
    rectangle6: makeNodeComponent("rectangle6"),
    frame12: makeNodeComponent("frame12"),
    address: makeNodeComponent("address"),
    phone: makeNodeComponent("phone"),
    email: makeNodeComponent("email"),
    ionCall: makeNodeComponent("ionCall"),
    logo1: makeNodeComponent("logo1"),
    header: makeNodeComponent("header"),
    rectangle1: makeNodeComponent("rectangle1"),
    component7: makeNodeComponent("component7"),
    rectangle8: makeNodeComponent("rectangle8"),
    component3: makeNodeComponent("component3"),
    rectangle9: makeNodeComponent("rectangle9"),
    facilities: makeNodeComponent("facilities"),
    rectangle10: makeNodeComponent("rectangle10"),
    component8: makeNodeComponent("component8"),
    rectangle11: makeNodeComponent("rectangle11"),
    research: makeNodeComponent("research"),
    group3: makeNodeComponent("group3"),
    component9: makeNodeComponent("component9"),
    rectangle22: makeNodeComponent("rectangle22"),
    rectangle23: makeNodeComponent("rectangle23"),
    component6: makeNodeComponent("component6"),
    rectangle7: makeNodeComponent("rectangle7"),
    datascienceLab1: makeNodeComponent("datascienceLab1"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
